# https://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-19.28

packages:
- .

extra-deps:
  #- aeson-1.5.6.0@sha256:5003bb6fd260d2e2d5a51dee2bf5c8e8f29e4e0e0288fef805c22dcc80ecab06,6788
